### ISSUE TITLE
Register User

### ISSUE THREAD

**Issue by matschl12** [OrganizeIT-FHCW/OrganizeIT#14]
The system should provide the user with the ability to register to the service.

**Comment by michael-mezgo** [comment]
FE working

**Comment by michael-mezgo** [comment]
![Bildschirmfoto 2024-01-21 um 23 14 14](https://github.com/OrganizeIT-FHCW/OrganizeIT/assets/58122000/a3b34fb8-c6f3-47f8-9e6a-2a79be90133d)
