### ISSUE TITLE
Log in User

### ISSUE THREAD

**Issue by matschl12** [OrganizeIT-FHCW/OrganizeIT#16]
Upon having registered to the service the system should provide the user with the ability to log in with an existing account.

**Comment by michael-mezgo** [comment]
FE working

**Comment by michael-mezgo** [comment]
![Bildschirmfoto 2024-01-21 um 23 14 11](https://github.com/OrganizeIT-FHCW/OrganizeIT/assets/58122000/9a31c8b0-8c98-465d-8cfd-6ffc634fa494)
